/* Generated By:JavaCC: Do not edit this line. ParserDefaultVisitor.java Version 7.0.2 */
package analyzer.ast;

public class ParserDefaultVisitor implements ParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTProgram node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTWhileStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDoWhileStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTWhileCond node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTWhileBlock node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIfStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIfCond node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIfBlock node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTElseBlock node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTForStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFunctionStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTReturnStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAssignStmt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAddition node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMulti node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIdentifier node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIntValue node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRealValue node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=b64248d3dc4002d91a19c3b5b6ead0c7 (do not edit this line) */
