/* Generated By:JavaCC: Do not edit this line. ParserVisitor.java Version 7.0.2 */
package analyzer.ast;

public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTWhileStmt node, Object data);
  public Object visit(ASTDoWhileStmt node, Object data);
  public Object visit(ASTWhileCond node, Object data);
  public Object visit(ASTWhileBlock node, Object data);
  public Object visit(ASTIfStmt node, Object data);
  public Object visit(ASTIfCond node, Object data);
  public Object visit(ASTIfBlock node, Object data);
  public Object visit(ASTElseBlock node, Object data);
  public Object visit(ASTForStmt node, Object data);
  public Object visit(ASTAssignStmt node, Object data);
  public Object visit(ASTMulti node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTIntValue node, Object data);
  public Object visit(ASTRealValue node, Object data);
}
/* JavaCC - OriginalChecksum=b5801a3de500dda8af51de4499cb5c3b (do not edit this line) */
