/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 7.0.2 */
package analyzer.ast;

public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTWHILESTMT = 2;
  public int JJTDOWHILESTMT = 3;
  public int JJTWHILECOND = 4;
  public int JJTWHILEBLOCK = 5;
  public int JJTIFSTMT = 6;
  public int JJTIFCOND = 7;
  public int JJTIFBLOCK = 8;
  public int JJTELSEBLOCK = 9;
  public int JJTFORSTMT = 10;
  public int JJTFUNCTIONSTMT = 11;
  public int JJTRETURNSTMT = 12;
  public int JJTASSIGNSTMT = 13;
  public int JJTADDITION = 14;
  public int JJTMULTI = 15;
  public int JJTIDENTIFIER = 16;
  public int JJTINTVALUE = 17;
  public int JJTREALVALUE = 18;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "WhileStmt",
    "DoWhileStmt",
    "WhileCond",
    "WhileBlock",
    "IfStmt",
    "IfCond",
    "IfBlock",
    "ElseBlock",
    "ForStmt",
    "FunctionStmt",
    "ReturnStmt",
    "AssignStmt",
    "Addition",
    "Multi",
    "Identifier",
    "IntValue",
    "RealValue",
  };
}
/* JavaCC - OriginalChecksum=000344bf4441f7e1ab05c5729851ccd5 (do not edit this line) */
