/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 7.0.2 */
package analyzer.ast;

public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTWHILESTMT = 2;
  public int JJTDOWHILESTMT = 3;
  public int JJTWHILECOND = 4;
  public int JJTWHILEBLOCK = 5;
  public int JJTIFSTMT = 6;
  public int JJTIFCOND = 7;
  public int JJTIFBLOCK = 8;
  public int JJTELSEBLOCK = 9;
  public int JJTASSIGNSTMT = 10;
  public int JJTIDENTIFIER = 11;
  public int JJTINTVALUE = 12;
  public int JJTREALVALUE = 13;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "WhileStmt",
    "DoWhileStmt",
    "WhileCond",
    "WhileBlock",
    "IfStmt",
    "IfCond",
    "IfBlock",
    "ElseBlock",
    "AssignStmt",
    "Identifier",
    "IntValue",
    "RealValue",
  };
}
/* JavaCC - OriginalChecksum=8a18d25891d2e78ac1bf49863c99e2b9 (do not edit this line) */
